### ISSUE TITLE
Collabora not working with nextcloud 11.

### ISSUE THREAD

**Issue by manuelteillet** [SnowMB/nextcloud#10]
Hello.

I'm using your collabora docker compose file for a small home nextcloud. It saved me lots of time, thanks.

As nexcloud has now an official dockerhub, I changed the image source from indiehosters to the new one and get nexcloud 11 working with no problem.

But I can't get collabora working with this setup. When I try to open an .odt file, I get a 504 Gateway Time-out error.

I saw some updates in collabora requesting some changes in nginx configuration but wasn't able to apply them. Could you help me please ?

Thanks.

**Comment by SnowMB** [comment]
Hey I'll look into it.

(It's been a while that I gave some love to this repo 😁  )

**Comment by SnowMB** [comment]
Hey @manuelteillet,

I need your help. I sucessfully tested my collabora setup with the newest version of the official nextcloud and collabora containers. Can you provide your (anonymous) `docker-compose.yml` file and nginx logs?

Any more information that might help find your error?

**Comment by manuelteillet** [comment]
In my docker-compose.yml, only the app section is different from yours and look like that: 
```
app:
    image: nextcloud:fpm
#    image: indiehosters/nextcloud
    container_name: nextcloud_fpm
    links:
      - db
    volumes:
      - ./nextcloud/apps:/var/www/html/apps
      - ./nextcloud/config:/var/www/html/config
      - /mnt/data/nextcloud:/var/www/html/data
    networks:
      - proxy-tier
    restart: always
```
Here are the anonymized docker logs from the moment I click until the error:
```
nextcloud_webserver      | 2017-04-12T21:00:23.563757366Z 172.18.0.3 - - [12/Apr/2017:21:00:23 +0000] "GET /index.php/apps/richdocuments/index?fileId=81_%2FDocuments&requesttoken=pjfUxEyxGcijhzIwX7E8OFRMmBFPViPY69u33u6K1UA%3D%3AkxyxkQrYKfjMzksEHP9PUxx7%2B3oADHu9g5rdjt7IkG8%3D HTTP/1.1" 499 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
proxy                    | 2017-04-12T21:00:23.565477074Z nginx.1    | nextcloud.example.com 77.84.228.18 - - [12/Apr/2017:21:00:23 +0000] "GET /index.php/apps/richdocuments/index?fileId=81_%2FDocuments&requesttoken=pjfUxEyxGcijhzIwX7E8OFRMmBFPViPY69u33u6K1UA%3D%3AkxyxkQrYKfjMzksEHP9PUxx7%2B3oADHu9g5rdjt7IkG8%3D HTTP/1.1" 499 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
nextcloud_fpm            | 2017-04-12T21:00:30.729126790Z 172.18.0.7 -  12/Apr/2017:21:00:30 +0000 "GET /ocs/v2.php" 200
proxy                    | 2017-04-12T21:00:30.737539734Z nginx.1    | nextcloud.example.com 77.84.228.18 - - [12/Apr/2017:21:00:30 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 74 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
nextcloud_webserver      | 2017-04-12T21:00:30.737203021Z 172.18.0.3 - - [12/Apr/2017:21:00:30 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 74 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
nextcloud_fpm            | 2017-04-12T21:01:00.736406259Z 172.18.0.7 -  12/Apr/2017:21:01:00 +0000 "GET /ocs/v2.php" 200
nextcloud_webserver      | 2017-04-12T21:01:00.743342571Z 172.18.0.3 - - [12/Apr/2017:21:01:00 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 74 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
proxy                    | 2017-04-12T21:01:00.746390794Z nginx.1    | nextcloud.example.com 77.84.228.18 - - [12/Apr/2017:21:01:00 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 74 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
nextcloud_webserver      | 2017-04-12T21:01:23.601643757Z 2017/04/12 21:01:23 [error] 5#5: *860915 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.3, server: , request: "GET /index.php/apps/richdocuments/index?fileId=81_%2FDocuments&requesttoken=pjfUxEyxGcijhzIwX7E8OFRMmBFPViPY69u33u6K1UA%3D%3AkxyxkQrYKfjMzksEHP9PUxx7%2B3oADHu9g5rdjt7IkG8%3D HTTP/1.1", upstream: "fastcgi://172.18.0.6:9000", host: "nextcloud.example.com"
proxy                    | 2017-04-12T21:01:23.605202229Z nginx.1    | nextcloud.example.com 77.84.228.18 - - [12/Apr/2017:21:01:23 +0000] "GET /index.php/apps/richdocuments/index?fileId=81_%2FDocuments&requesttoken=pjfUxEyxGcijhzIwX7E8OFRMmBFPViPY69u33u6K1UA%3D%3AkxyxkQrYKfjMzksEHP9PUxx7%2B3oADHu9g5rdjt7IkG8%3D HTTP/1.1" 504 184 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
nextcloud_webserver      | 2017-04-12T21:01:23.606264477Z 172.18.0.3 - - [12/Apr/2017:21:01:23 +0000] "GET /index.php/apps/richdocuments/index?fileId=81_%2FDocuments&requesttoken=pjfUxEyxGcijhzIwX7E8OFRMmBFPViPY69u33u6K1UA%3D%3AkxyxkQrYKfjMzksEHP9PUxx7%2B3oADHu9g5rdjt7IkG8%3D HTTP/1.1" 504 184 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
proxy                    | 2017-04-12T21:01:23.606524505Z nginx.1    | 2017/04/12 21:01:23 [error] 39#39: *422405 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 77.84.228.18, server: nextcloud.example.com, request: "GET /index.php/apps/richdocuments/index?fileId=81_%2FDocuments&requesttoken=pjfUxEyxGcijhzIwX7E8OFRMmBFPViPY69u33u6K1UA%3D%3AkxyxkQrYKfjMzksEHP9PUxx7%2B3oADHu9g5rdjt7IkG8%3D HTTP/1.1", upstream: "http://172.18.0.7:80/index.php/apps/richdocuments/index?fileId=81_%2FDocuments&requesttoken=pjfUxEyxGcijhzIwX7E8OFRMmBFPViPY69u33u6K1UA%3D%3AkxyxkQrYKfjMzksEHP9PUxx7%2B3oADHu9g5rdjt7IkG8%3D", host: "nextcloud.example.com"
```
And here is the collabora container log at startup:
```
collabora                | 2017-04-12T21:49:36.707291879Z Generating RSA private key, 2048 bit long modulus
collabora                | 2017-04-12T21:49:36.961713421Z .....................+++
collabora                | 2017-04-12T21:49:37.154085112Z ...............................+++
collabora                | 2017-04-12T21:49:37.156558233Z e is 65537 (0x10001)
collabora                | 2017-04-12T21:49:37.207692040Z Generating RSA private key, 2048 bit long modulus
collabora                | 2017-04-12T21:49:37.310253699Z ...............+++
collabora                | 2017-04-12T21:49:37.858259355Z ..................................................................................................+++
collabora                | 2017-04-12T21:49:37.859280821Z e is 65537 (0x10001)
collabora                | 2017-04-12T21:49:37.908069131Z Signature ok
collabora                | 2017-04-12T21:49:37.908179419Z subject=/C=DE/ST=BW/L=Stuttgart/O=Dummy Authority/CN=localhost
collabora                | 2017-04-12T21:49:37.909166506Z Getting CA Private Key
collabora                | 2017-04-12T21:49:38.060248018Z loolforkit version details: 2.0.4 - 2.0.4
collabora                | 2017-04-12T21:49:40.098876959Z office version details: { "ProductName": "Collabora Office", "ProductVersion": "5.1", "ProductExtension": ".10.21", "BuildId": "e91d2c2d59b035e40bdefac5fe06fb210180ed86" }
```
In my nextcloud collabora configuration tab, I put my collabora domain without port:
`https://collabora.example.com`

Thanks for your help. Let me know if you need anything else.

**Comment by SnowMB** [comment]
Hey,
configuration looks good to me. Maybe you can check if the variable substition is working correctly by running:

```
docker-compose config
```

You should see your docker-compose file with the values from the .env file (might be reordered).

Make sure that all containers are up and not exited / restarting:

```
docker-compose ps
```

Then you might check that your nginx-proxy config is generated correctly:

```
docker-compose exec proxy cat /etc/nginx/conf.d/default.conf
```

**Comment by manuelteillet** [comment]
Hey,
here is my docker-compose config : 
```
networks:
  proxy-tier:
    external:
      name: nginx-proxy
services:
  app:
    container_name: nextcloud_fpm
    image: nextcloud:fpm
    links:
    - db
    networks:
      proxy-tier: null
    restart: always
    volumes:
    - /opt/nextcloud/collabora/nextcloud/apps:/var/www/html/apps:rw
    - /opt/nextcloud/collabora/nextcloud/config:/var/www/html/config:rw
    - /mnt/data/nextcloud:/var/www/html/data:rw
  collabora:
    cap_add:
    - MKNOD
    container_name: collabora
    environment:
      LETSENCRYPT_EMAIL: my.email@gmail.com
      LETSENCRYPT_HOST: collabora.example.com
      VIRTUAL_HOST: collabora.example.com
      VIRTUAL_NETWORK: nginx-proxy
      VIRTUAL_PORT: '9980'
      VIRTUAL_PROTO: https
      domain: nextcloud.example.com
    expose:
    - 9980
    image: collabora/code
    networks:
      proxy-tier: null
    restart: always
  db:
    container_name: db
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: nextcloud
    image: mariadb
    networks:
      proxy-tier: null
    restart: always
    volumes:
    - /opt/nextcloud/collabora/nextcloud/db:/var/lib/mysql:rw
  letsencrypt-companion:
    container_name: letsencrypt-companion
    image: alastaircoote/docker-letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /opt/nextcloud/collabora/proxy/certs:/etc/nginx/certs:rw
    volumes_from:
    - service:proxy:rw
  proxy:
    container_name: proxy
    image: jwilder/nginx-proxy
    networks:
      proxy-tier: null
    ports:
    - 80:80
    - 443:443
    restart: always
    volumes:
    - /opt/nextcloud/collabora/proxy/conf.d:/etc/nginx/conf.d:rw
    - /opt/nextcloud/collabora/proxy/vhost.d:/etc/nginx/vhost.d:rw
    - /opt/nextcloud/collabora/proxy/html:/usr/share/nginx/html:rw
    - /opt/nextcloud/collabora/proxy/certs:/etc/nginx/certs:ro
    - /var/run/docker.sock:/tmp/docker.sock:ro
  redis:
    container_name: redis
    image: redis
    networks:
      proxy-tier: null
    restart: always
  web:
    container_name: nextcloud_webserver
    environment:
      LETSENCRYPT_EMAIL: my.email@gmail.com
      LETSENCRYPT_HOST: nextcloud.example.com
      VIRTUAL_HOST: nextcloud.example.com
      VIRTUAL_NETWORK: nginx-proxy
      VIRTUAL_PORT: '80'
    image: nginx
    links:
    - app
    networks:
      proxy-tier: null
    restart: always
    volumes:
    - /opt/nextcloud/collabora/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
    - service:app:rw
version: '2.0'
volumes: {}
```
My docker-compose ps : 
```
        Name                      Command              State                    Ports                  
------------------------------------------------------------------------------------------------------
collabora              /bin/sh -c bash start-libr      Up      9980/tcp                                
                       ...                                                                             
db                     docker-entrypoint.sh mysqld     Up      3306/tcp                                
letsencrypt-           /bin/bash /app/entrypoint.      Up                                              
companion              ...                                                                             
nextcloud_fpm          /entrypoint.sh php-fpm          Up      9000/tcp                                
nextcloud_webserver    nginx -g daemon off;            Up      443/tcp, 80/tcp                         
proxy                  /app/docker-entrypoint.sh       Up      0.0.0.0:443->443/tcp,                   
                       ...                                     0.0.0.0:80->80/tcp                      
redis                  docker-entrypoint.sh redis      Up      6379/tcp    
```
And my docker-compose exec proxy cat /etc/nginx/conf.d/default.conf : 
```
networks:
  proxy-tier:
    external:
      name: nginx-proxy
services:
  app:
    container_name: nextcloud_fpm
    image: nextcloud:fpm
    links:
    - db
    networks:
      proxy-tier: null
    restart: always
    volumes:
    - /opt/nextcloud/collabora/nextcloud/apps:/var/www/html/apps:rw
    - /opt/nextcloud/collabora/nextcloud/config:/var/www/html/config:rw
    - /mnt/data/nextcloud:/var/www/html/data:rw
  collabora:
    cap_add:
    - MKNOD
    container_name: collabora
    environment:
      LETSENCRYPT_EMAIL: my.email@gmail.com
      LETSENCRYPT_HOST: collabora.example.com
      VIRTUAL_HOST: collabora.example.com
      VIRTUAL_NETWORK: nginx-proxy
      VIRTUAL_PORT: '9980'
      VIRTUAL_PROTO: https
      domain: nextcloud.example.com
    expose:
    - 9980
    image: collabora/code
    networks:
      proxy-tier: null
    restart: always
  db:
    container_name: db
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: nextcloud
    image: mariadb
    networks:
      proxy-tier: null
    restart: always
    volumes:
    - /opt/nextcloud/collabora/nextcloud/db:/var/lib/mysql:rw
  letsencrypt-companion:
    container_name: letsencrypt-companion
    image: alastaircoote/docker-letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /opt/nextcloud/collabora/proxy/certs:/etc/nginx/certs:rw
    volumes_from:
    - service:proxy:rw
  proxy:
    container_name: proxy
    image: jwilder/nginx-proxy
    networks:
      proxy-tier: null
    ports:
    - 80:80
    - 443:443
    restart: always
    volumes:
    - /opt/nextcloud/collabora/proxy/conf.d:/etc/nginx/conf.d:rw
    - /opt/nextcloud/collabora/proxy/vhost.d:/etc/nginx/vhost.d:rw
    - /opt/nextcloud/collabora/proxy/html:/usr/share/nginx/html:rw
    - /opt/nextcloud/collabora/proxy/certs:/etc/nginx/certs:ro
    - /var/run/docker.sock:/tmp/docker.sock:ro
  redis:
    container_name: redis
    image: redis
    networks:
      proxy-tier: null
    restart: always
  web:
    container_name: nextcloud_webserver
    environment:
      LETSENCRYPT_EMAIL: my.email@gmail.com
      LETSENCRYPT_HOST: nextcloud.example.com
      VIRTUAL_HOST: nextcloud.example.com
      VIRTUAL_NETWORK: nginx-proxy
      VIRTUAL_PORT: '80'
    image: nginx
    links:
    - app
    networks:
      proxy-tier: null
    restart: always
    volumes:
    - /opt/nextcloud/collabora/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
    - service:app:rw
version: '2.0'
volumes: {}
```
I don't know nginx configuration but everything looks fine to me.
I tried to add a username and password to the collabora container in docker-compose.yml and after a restart, I can successfully connect to the admin interface at the address : https://collabora.example.com/loleaflet/dist/admin/admin.html
I'm running my server on archlinnux on a slow machine.(amd e-350).
If I add 9980 port after my collabora address in nextcloud config, I get a "forbidden access" nextcloud error instead of the nginx timeout.

Thanks for your time. If you can figure any lead to a solution, let me know.
